CREATE TABLE [dbo].[AM100_CASES_BAK_050315] (
    [SEQ_CTR]               INT              IDENTITY (1, 1) NOT NULL,
    [CASE_ID]               NCHAR (64)       NOT NULL,
    [ID]                    UNIQUEIDENTIFIER NULL,
    [TS]                    ROWVERSION       NULL,
    [INTAKE_DATE]           DATE             CONSTRAINT [DF_AM100_CASES_BAK_050315_INTAKE_DATE] DEFAULT (getdate()) NULL,
    [EDIT_DATE]             DATE             NULL,
    [LAST_TEST_DATE]        DATE             NULL,
    [NEXT_TEST_DATE]        DATE             NULL,
    [FIRST_VISIT_DATE]      DATE             NULL,
    [SECOND_VISIT_DATE]     DATE             NULL,
    [THIRD_VISIT_DATE]      DATE             NULL,
    [FOURTH_VISIT_DATE]     DATE             NULL,
    [RETEST_DATE]           DATE             NULL,
    [TESTKIT_LOT_NUMBER]    NCHAR (20)       NULL,
    [TESTKIT_LOT_DATE]      DATE             NULL,
    [FAX_RECD_DATE]         DATE             NULL,
    [DIST_ID]               NCHAR (32)       NULL,
    [SUBDIST_ID]            NCHAR (32)       CONSTRAINT [DF_AM100_CASES_BAK_050315_SUBDIST_ID] DEFAULT (N'NONE') NULL,
    [REP_ID]                NCHAR (32)       NULL,
    [SUBREP_ID]             NCHAR (32)       CONSTRAINT [DF_AM100_CASES_BAK_050315_SUBREP_ID] DEFAULT (N'NONE') NULL,
    [PROVIDER_ID]           NCHAR (32)       NULL,
    [PATIENT_DIRECT_FLAG]   CHAR (1)         NULL,
    [BILLTO_ACCTG_ID]       NCHAR (255)      NULL,
    [BILLTO_ACCTG_NAME]     NVARCHAR (64)    NULL,
    [BILLTO_ADD1]           NVARCHAR (64)    NULL,
    [BILLTO_ADD2]           NVARCHAR (64)    NULL,
    [BILLTO_ADD3]           NVARCHAR (64)    NULL,
    [BILLTO_ADD4]           NVARCHAR (64)    NULL,
    [BILLTO_ADD5]           NVARCHAR (64)    NULL,
    [SHIPTO_ACCTG_ID]       NCHAR (255)      NULL,
    [SHIPTO_ACCTG_NAME]     NVARCHAR (64)    NULL,
    [SHIPTO_ADD1]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD2]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD3]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD4]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD5]           NVARCHAR (64)    NULL,
    [SHIPTO_CITY]           NCHAR (32)       NULL,
    [SHIPTO_STATE]          NCHAR (8)        NULL,
    [SHIPTO_POSTAL]         NCHAR (12)       NULL,
    [RESULTS_IMAGE_PATH]    NVARCHAR (128)   NULL,
    [RESULTS_IMAGE_FILE]    NCHAR (32)       NULL,
    [CONSENT_OK]            NCHAR (1)        CONSTRAINT [DF_AM100_CASES_BAK_050315_CONSENT_OK] DEFAULT (N'N') NULL,
    [RX_OK]                 NCHAR (1)        CONSTRAINT [DF_AM100_CASES_BAK_050315_RX_OK] DEFAULT (N'N') NULL,
    [RESULTS_OK]            NCHAR (1)        CONSTRAINT [DF_AM100_CASES_BAK_050315_RESULTS_OK] DEFAULT (N'N') NULL,
    [FINAL_OK]              NCHAR (1)        NULL,
    [PatientLastName]       NVARCHAR (32)    NULL,
    [PatientFirstName]      NVARCHAR (32)    NULL,
    [PatientMI]             NVARCHAR (1)     NULL,
    [PATIENT_NAME]          NCHAR (70)       NULL,
    [PatientAddressLine1]   VARCHAR (50)     NULL,
    [PatientAddressLine2]   VARCHAR (50)     NULL,
    [PatientCity]           NVARCHAR (25)    NULL,
    [PatientState]          NVARCHAR (10)    NULL,
    [PatientZipCode]        NVARCHAR (12)    NULL,
    [PatientCountry]        NVARCHAR (50)    NULL,
    [PatientBillingAddress] NVARCHAR (25)    NULL,
    [PatientBillingCity]    NVARCHAR (25)    NULL,
    [PatientBillingState]   NVARCHAR (10)    NULL,
    [PatientBillingZipCode] NVARCHAR (10)    NULL,
    [PatientHomePhone]      NVARCHAR (14)    NULL,
    [PatientWorkPhone]      NVARCHAR (14)    NULL,
    [PatientFax]            NVARCHAR (14)    NULL,
    [PatientEmail]          NCHAR (64)       NULL,
    [Gender]                NVARCHAR (1)     NULL,
    [Birthdate]             DATETIME         NULL,
    [AccountNumber]         NVARCHAR (10)    NULL,
    [MedicalRecordNum]      NVARCHAR (10)    NULL,
    [Notes]                 NTEXT            NULL,
    [ChargeAccount]         BIT              NULL,
    [PatInsID]              NVARCHAR (32)    NULL,
    [SSN]                   NVARCHAR (25)    NULL,
    [Spanish]               CHAR (1)         NULL,
    [HIPPA]                 BIT              NULL,
    [HIPPADATE]             DATETIME         NULL,
    [AutoCharge]            BIT              NULL,
    [FacilityID]            INT              NULL,
    [CCNumber]              VARCHAR (25)     NULL,
    [CCExpMonth]            VARCHAR (2)      NULL,
    [CCExpYear]             VARCHAR (2)      NULL,
    [CCName]                VARCHAR (41)     NULL,
    [CCAddress]             VARCHAR (41)     NULL,
    [CCZip]                 VARCHAR (41)     NULL,
    [CCAddressSame]         CHAR (1)         NULL,
    [DateChanged]           DATETIME         NULL,
    [DateUploaded]          DATETIME         NULL,
    [BeginBalance]          FLOAT (53)       NULL,
    [Password]              VARCHAR (50)     NULL,
    [HIPPASignatureID]      INT              NULL,
    [CustomField1]          VARCHAR (100)    NULL,
    [CustomField2]          VARCHAR (100)    NULL,
    [CustomField3]          VARCHAR (100)    NULL,
    [CustomField4]          VARCHAR (100)    NULL,
    [CustomField5]          VARCHAR (100)    NULL,
    [CustomField6]          VARCHAR (100)    NULL,
    [CustomField7]          VARCHAR (100)    NULL,
    [CustomField8]          VARCHAR (100)    NULL,
    [CustomField9]          VARCHAR (100)    NULL,
    [CustomField10]         VARCHAR (100)    NULL,
    [IDQualifier]           VARCHAR (2)      NULL,
    [LastRXDate]            NCHAR (10)       NULL,
    [CycleFill]             BIT              NULL,
    [CycleFillInterval]     INT              NULL,
    [RXDuration]            INT              NULL,
    [RXExpDate]             DATE             NULL,
    [FirstCycleShipDate]    DATE             NULL,
    [FirstCycleOrder]       INT              NULL,
    [EndCycleShipDate]      DATE             NULL,
    [LastCycleShipDate]     DATETIME         NULL,
    [LastCycleOrder]        INT              NULL,
    [NextCycleShipDate]     DATETIME         NULL,
    [NextCycleOrder]        INT              NULL,
    CONSTRAINT [PK_AM100_CASES_BAK_050315_1] PRIMARY KEY CLUSTERED ([SEQ_CTR] ASC)
);

