CREATE TABLE [dbo].[AM400_SO_HEADER] (
    [SEQ_CTR]                  INT              IDENTITY (1, 1) NOT NULL,
    [ID]                       UNIQUEIDENTIFIER NULL,
    [TS]                       ROWVERSION       NULL,
    [FK_AM300_SEQ_CTR]         INT              NULL,
    [EXPORTED_TO_ACCTG_FLAG]   CHAR (1)         NULL,
    [EXPORT_VALIDATION_STATUS] NCHAR (64)       NULL,
    [SALES_ORDER_NUMBER]       NCHAR (32)       NULL,
    [PURCHASE_ORDER_NUMBER]    NCHAR (32)       NULL,
    [SALES_ORDER_CLOSED_FLAG]  NCHAR (1)        NULL,
    [SALES_ORDER_COMMENTS]     NCHAR (128)      NULL,
    [PRACTITIONER_NAME]        NCHAR (42)       NULL,
    [PROVIDER_ID]              NVARCHAR (32)    NULL,
    [EMAIL]                    NCHAR (64)       NULL,
    [PATIENT_DIRECT_FLAG]      CHAR (1)         NULL,
    [BILLTO_ACCTG_ID]          NCHAR (255)      NULL,
    [BILLTO_ACCTG_NAME]        NVARCHAR (34)    NULL,
    [BILLTO_ADD1]              NVARCHAR (64)    NULL,
    [BILLTO_ADD2]              NVARCHAR (64)    NULL,
    [BILLTO_ADD3]              NVARCHAR (64)    NULL,
    [BILLTO_ADD4]              NVARCHAR (64)    NULL,
    [BILLTO_ADD5]              NVARCHAR (64)    NULL,
    [SHIPTO_ACCTG_ID]          NCHAR (255)      NULL,
    [SHIPTO_ACCTG_NAME]        NVARCHAR (64)    NULL,
    [SHIPTO_ADD1]              NVARCHAR (64)    NULL,
    [SHIPTO_ADD2]              NVARCHAR (64)    NULL,
    [SHIPTO_ADD3]              NVARCHAR (64)    NULL,
    [SHIPTO_ADD4]              NVARCHAR (64)    NULL,
    [SHIPTO_ADD5]              NVARCHAR (64)    NULL,
    [SHIPTO_CITY]              NCHAR (32)       NULL,
    [SHIPTO_STATE]             NCHAR (8)        NULL,
    [SHIPTO_POSTAL]            NCHAR (12)       NULL,
    [ORDER_CONF_TEMPLATE]      NCHAR (32)       NULL,
    [SALES_ORDER_TEMPLATE]     NCHAR (64)       NULL,
    [DIST_ID]                  NCHAR (32)       NULL,
    [DIST_INITIALS]            CHAR (6)         NULL,
    [SUBDIST_ID]               NCHAR (32)       NULL,
    [REP_ID]                   NCHAR (32)       NULL,
    [SUBREP_ID]                NCHAR (32)       NULL,
    [ORDER_NUMBER]             NCHAR (20)       NULL,
    [ORDER_DATE]               DATE             NULL,
    CONSTRAINT [PK_AM400_SO_HEADER] PRIMARY KEY CLUSTERED ([SEQ_CTR] ASC)
);

