CREATE TABLE [dbo].[AM900_PROVIDER_LOOKUP_BUFFER] (
    [SEQ_CTR]                INT              NOT NULL,
    [SEQ_CTR_1]              INT              IDENTITY (1, 1) NOT NULL,
    [ID]                     UNIQUEIDENTIFIER NULL,
    [DIST_ID]                NCHAR (32)       NULL,
    [SUBDIST_ID]             NCHAR (32)       NULL,
    [REP_ID]                 NCHAR (32)       NULL,
    [SUBREP_ID]              NCHAR (32)       CONSTRAINT [DF_AM900_PROVIDER_LOOKUP_BUFFER_SUBREP_ID] DEFAULT (N'NONE') NULL,
    [PHYSICIAN_ID]           NCHAR (32)       NULL,
    [PROVIDER_ID]            NVARCHAR (32)    NULL,
    [PROVIDER_FULL_ID]       NCHAR (198)      NULL,
    [PracticeName]           NVARCHAR (30)    NULL,
    [PROVIDER0_FNAME]        NCHAR (20)       NULL,
    [PROVIDER0_LNAME]        NCHAR (20)       NULL,
    [Provider0Name]          NVARCHAR (42)    NULL,
    [Provider0Email]         NVARCHAR (50)    NULL,
    [Provider0DEA]           NVARCHAR (14)    NULL,
    [Provider0StateLic]      VARCHAR (20)     NULL,
    [Provider0NPI]           VARCHAR (20)     NULL,
    [BILLTO_ACCTG_ID]        NCHAR (255)      NULL,
    [BILLTO_ACCTG_NAME]      NVARCHAR (32)    NULL,
    [BILLTO_ADD1]            NVARCHAR (64)    NULL,
    [BILLTO_ADD2]            NVARCHAR (64)    NULL,
    [BILLTO_ADD3]            NVARCHAR (64)    NULL,
    [BILLTO_ADD4]            NVARCHAR (64)    NULL,
    [BILLTO_ADD5]            NVARCHAR (64)    NULL,
    [SHIPTO_ACCTG_ID]        NCHAR (255)      NULL,
    [SHIPTO_ACCTG_NAME]      NVARCHAR (64)    NULL,
    [SHIPTO_ADD1]            NVARCHAR (64)    NULL,
    [SHIPTO_ADD2]            NVARCHAR (64)    NULL,
    [SHIPTO_ADD3]            NVARCHAR (64)    NULL,
    [SHIPTO_ADD4]            NVARCHAR (64)    NULL,
    [SHIPTO_ADD5]            NVARCHAR (64)    NULL,
    [Telephone1]             NVARCHAR (15)    NULL,
    [Telephone2]             NVARCHAR (15)    NULL,
    [FaxNumber]              NVARCHAR (15)    NULL,
    [Comments]               NTEXT            NULL,
    [PROVIDER1_FNAME]        NCHAR (20)       NULL,
    [PROVIDER1_LNAME]        NCHAR (20)       NULL,
    [Provider1Name]          NVARCHAR (42)    NULL,
    [Provider1Email]         NVARCHAR (50)    NULL,
    [Provider1DEA]           NVARCHAR (14)    NULL,
    [Provider1StateLic]      VARCHAR (20)     NULL,
    [Provider1NPI]           VARCHAR (20)     NULL,
    [PROVIDER2_FNAME]        NCHAR (20)       NULL,
    [PROVIDER2_LNAME]        NCHAR (20)       NULL,
    [Provider2Name]          NVARCHAR (42)    NULL,
    [Provider2Email]         NCHAR (50)       NULL,
    [Provider2DEA]           VARCHAR (20)     NULL,
    [Provider2StateLic]      VARCHAR (20)     NULL,
    [Provider2NPI]           VARCHAR (20)     NULL,
    [PrimaryContactName]     NCHAR (30)       NULL,
    [PrimaryContactTitle]    NCHAR (64)       NULL,
    [PrimaryContactEmail]    NCHAR (64)       NULL,
    [SpecialInsts]           NCHAR (128)      NULL,
    [OtherStaff1Name]        NCHAR (64)       NULL,
    [OtherStaff1Title]       NCHAR (64)       NULL,
    [OtherStaff1Lic]         NCHAR (20)       NULL,
    [OtherStaff2Name]        NCHAR (64)       NULL,
    [OtherStaff2Title]       NCHAR (64)       NULL,
    [OtherStaff2Lic]         NCHAR (20)       NULL,
    [PrescriberLocationCode] VARCHAR (3)      NULL,
    [LastRXDate]             DATE             NULL,
    [LastTestKitDate]        DATE             NULL,
    [NumberofScripts]        FLOAT (53)       NULL,
    [ImportID]               INT              NULL,
    [UserName]               NVARCHAR (50)    NULL,
    [Password]               NVARCHAR (50)    NULL,
    [DateEntered]            DATETIME         NULL,
    [DateChanged]            DATETIME         NULL,
    [DateUploaded]           DATETIME         NULL,
    [StateIssued]            VARCHAR (15)     NULL,
    [SPI]                    NVARCHAR (50)    NULL,
    [PriceAmount]            FLOAT (53)       NULL,
    [DoctorImage]            IMAGE            NULL,
    [FaxRequests]            BIT              NULL,
    [DoctorCode]             NVARCHAR (4)     NULL,
    [PrimaryID]              INT              NULL,
    [PrimaryName]            NVARCHAR (120)   NULL,
    [Deleted]                BIT              NULL,
    [SalesRep]               INT              NULL,
    [ShippingAddressLine1]   NVARCHAR (30)    NULL,
    [ShippingAddressLine2]   NVARCHAR (30)    NULL,
    [ShippingCity]           NVARCHAR (20)    NULL,
    [ShippingState]          NVARCHAR (2)     NULL,
    [ShippingZip]            NVARCHAR (15)    NULL,
    [ShippingCountry]        NVARCHAR (25)    NULL,
    [Country]                NVARCHAR (25)    NULL,
    [TIME_STAMP]             ROWVERSION       NULL,
    [ORDER_CONF_TEMPLATE]    CHAR (40)        NULL,
    [DIST_ID1]               NCHAR (32)       NULL,
    [SUBDIST_ID1]            NCHAR (32)       NULL,
    [REP_ID1]                NCHAR (32)       NULL,
    [BILLTO_ACCTG_ID1]       NCHAR (255)      NULL,
    [SHIPTO_ACCTG_ID1]       NCHAR (255)      NULL,
    [PROVIDER_ID1]           NVARCHAR (32)    NULL,
    [PROVIDER_FULL_ID1]      NCHAR (198)      NULL,
    [BILLTO_ACCTG_NAME1]     NCHAR (64)       NULL,
    [BILLTO_ADD11]           NVARCHAR (64)    NULL,
    [BILLTO_ADD21]           NVARCHAR (64)    NULL,
    [BILLTO_ADD31]           NVARCHAR (64)    NULL,
    [BILLTO_ADD41]           NVARCHAR (64)    NULL,
    [BILLTO_ADD51]           NVARCHAR (64)    NULL,
    [SHIPTO_ACCTG_NAME1]     NVARCHAR (64)    NULL,
    [SHIPTO_ADD11]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD21]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD31]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD41]           NVARCHAR (64)    NULL,
    [SHIPTO_ADD51]           NVARCHAR (64)    NULL,
    CONSTRAINT [PK_AM900_PROVIDER_LOOKUP_BUFFER_1] PRIMARY KEY CLUSTERED ([SEQ_CTR_1] ASC)
);

