CREATE TABLE [dbo].[AM915A_ROOT_NAME_LOOKUP] (
    [SEQ_CTR]             INT        IDENTITY (1, 1) NOT NULL,
    [ROOT_NAME]           CHAR (255) NOT NULL,
    [TS]                  ROWVERSION NOT NULL,
    [PATIENT_DIRECT_FLAG] CHAR (1)   NOT NULL,
    CONSTRAINT [PK_AM915A_ROOT_NAME_LOOKUP_1] PRIMARY KEY CLUSTERED ([SEQ_CTR] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_AM915A_ROOT_NAME_LOOKUP]
    ON [dbo].[AM915A_ROOT_NAME_LOOKUP]([SEQ_CTR] ASC);

