CREATE TABLE [dbo].[AM920A_ITEM_TYPE] (
    [ITEM_TYPE_ID]   INT        NOT NULL,
    [ITEM_TYPE_DESC] NCHAR (64) NULL,
	CONSTRAINT [PK_AM920_ITEM_TYPE] PRIMARY KEY CLUSTERED ([ITEM_TYPE_ID] ASC)
);

