CREATE TABLE [dbo].[AM960_MONTH_LOOKUP] (
    [MONTH_NUMBER] INT       NOT NULL,
    [MONTH_NAME]   NCHAR (3) NOT NULL,
    CONSTRAINT [PK_AM960_MONTH_LOOKUP] PRIMARY KEY CLUSTERED ([MONTH_NUMBER] ASC, [MONTH_NAME] ASC)
);

