CREATE TABLE [dbo].[AM965_STATE_LOOKUP] (
	[SEQ_CTR]	INT           IDENTITY (1, 1) NOT NULL,
    [Code]		CHAR (2)     NULL,
    [Name]		VARCHAR (50) NULL,
	CONSTRAINT [PK_AM965_STATE_LOOKUP] PRIMARY KEY CLUSTERED (SEQ_CTR ASC)
);

